name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [
            '7.4',
            '8.1'
        ]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer validate
        run: composer validate

      - name: Composer get cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Composer install
        run: |
          composer --version
          composer install --optimize-autoloader

      - name: Run tests
        run: |
          if [[ ${{ matrix.php-version }} == '7.4' ]]; then
           XDEBUG_MODE=coverage vendor/bin/phpunit tests/ --coverage-clover coverage.xml
          else
           composer tests
          fi

